#pragma once

// For use by JK Game Engine applications

#include "Game Engine/EngineManager.h"
#include "Game Engine/Input.h"
#include "Game Engine/Texture.h"
#include "Game Engine/SceneManager.h"
#include "Game Engine/Scene.h"
#include "Game Engine/GameObject/Components/Camera.h"
#include "Game Engine/CommonValues.h"
#include "Game Engine/DirectionalLight.h"
#include "Game Engine/Light.h"
#include "Game Engine/Material.h"
#include "Game Engine/Mesh.h"
#include "Game Engine/Model.h"
#include "Game Engine/PointLight.h"
#include "Game Engine/Shader.h"
#include "Game Engine/SpotLight.h"
#include "Game Engine/TransformLegacy.h"
#include "Game Engine/Window.h"
#include "Game Engine/GameObject/GameObject.h"
#include "Game Engine/GameObject/BaseComponent.h"
#include "Game Engine/GameObject/Components/MeshRenderer.h"
#include "Game Engine/GameObject/Components/Transform.h"
#include "Game Engine/Time.h"
#include "Game Engine/Enums.h"
#include "Game Engine/Skybox.h"
#include "Game Engine/ShadowMap.h"
#include "Game Engine/OmniShadowMap.h"
#include "Game Engine/AssetLoader.h"
#include "Game Engine/AssetCache.h"
#include "Game Engine/SceneLoader.h"